{
    "status": "FAILURE",
    "traceback": "Traceback (most recent call last):\n  File \"/cpfs01/shared/MOE/fengqiantai/qtfeng/miniconda3/envs/foldbench/libexec/openstructure/ost-compare-ligand-structures\", line 711, in _Main\n    out = _Process(cleaned_model, cleaned_model_ligands,\n  File \"/cpfs01/shared/MOE/fengqiantai/qtfeng/miniconda3/envs/foldbench/libexec/openstructure/ost-compare-ligand-structures\", line 453, in _Process\n    lddtpli_scorer = _SetupLDDTPLIScorer(model, model_ligands,\n  File \"/cpfs01/shared/MOE/fengqiantai/qtfeng/miniconda3/envs/foldbench/libexec/openstructure/ost-compare-ligand-structures\", line 420, in _SetupLDDTPLIScorer\n    return ligand_scoring_lddtpli.LDDTPLIScorer(model, reference,\n  File \"/cpfs01/shared/MOE/fengqiantai/qtfeng/miniconda3/envs/foldbench/lib/python3.9/site-packages/ost/mol/alg/ligand_scoring_lddtpli.py\", line 110, in __init__\n    super().__init__(model, target, model_ligands = model_ligands,\n  File \"/cpfs01/shared/MOE/fengqiantai/qtfeng/miniconda3/envs/foldbench/lib/python3.9/site-packages/ost/mol/alg/ligand_scoring_base.py\", line 243, in __init__\n    raise ValueError(\"No ligand in the model and in the target\")\nValueError: No ligand in the model and in the target\n",
    "exception": "ValueError: No ligand in the model and in the target\n"
}